#!/usr/bin/env bash
# configures a new Ubuntu machine installing Nginx
sudo apt-get -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP' # Allow for the port 80
sudo echo "Holberton School" > index.html
sudo mv index.html /var/www/html/
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

new_Argument="server_name _;\n\trewrite ^\/redirect_me cbarreiro.tech permanent;"
narg1="\n\tadd_header X-Served-By \$hostname;"
narg2="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new_argument$narg1$narg2/" /etc/nginx/sites-enabled/default

service nginx restart
