#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
apt-get update -y
apt-get install -y haproxy

CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 1206-web-01 34.73.70.32:80 check
	server 1206-web-02 3.85.244.69:80 check
"

sudo echo "$CONF" | sudo tee -a  /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start