#!/usr/bin/env bash
#script that gives you information about the holbertonschool file
#This file indicate that if the file exit , not exit or It is empty

FILE=holbertonschool

if [ -e $FILE ]; then
    echo "${FILE} file exists"

    if [ -s $FILE ]; then
	echo "${FILE} file is not empty"
    else
	echo "${FILE} file is empty"
    fi

    if [ -f $FILE ]; then
        echo "${FILE} is a regular file"
    fi

else
    echo 'holbertonschool file does not exist'
fi
